export {CalendarComponent} from "./calendar/calendar.component"
export {BodyComponent} from "./body/body.component"
export {ChartjsComponent} from "./chartjs/chartjs.component"
export {DataTComponent} from "./data-t/data-t.component"
export {MailComponent} from "./mail/mail.component"
export {WidgetsComponent} from "./widgets/widgets.component"
export {FormsComponent} from "./forms/forms.component"
export {Form2Component} from "./form2/form2.component"